/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAgentAssistant: typeof import('./src/components/AdminAgentAssistant.vue')['default']
    AdminUploadCard: typeof import('./src/components/admin/AdminUploadCard.vue')['default']
    AIFieldAssistant: typeof import('./src/components/AIFieldAssistant.vue')['default']
    AppBreadcrumbs: typeof import('./src/components/AppBreadcrumbs.vue')['default']
    AuthDebugDashboard: typeof import('./src/components/AuthDebugDashboard.vue')['default']
    CandidateChecklist: typeof import('./src/components/CandidateChecklist.vue')['default']
    CandidateSearchBar: typeof import('./src/components/search/CandidateSearchBar.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ChatNotificationFloat: typeof import('./src/components/ChatNotificationFloat.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GeminiChat: typeof import('./src/components/GeminiChat.vue')['default']
    GlobalLoader: typeof import('./src/components/GlobalLoader.vue')['default']
    INEPPeriodSection: typeof import('./src/components/specialty/INEPPeriodSection.vue')['default']
    LottieAnimation: typeof import('./src/components/LottieAnimation.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PepFloatingWindow: typeof import('./src/components/PepFloatingWindow.vue')['default']
    PepSideView: typeof import('./src/components/PepSideView.vue')['default']
    PerformanceChart: typeof import('./src/components/PerformanceChart.vue')['default']
    RankingCard: typeof import('./src/components/RankingCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
    SequentialConfigPanel: typeof import('./src/components/sequential/SequentialConfigPanel.vue')['default']
    SimulationControls: typeof import('./src/components/SimulationControls.vue')['default']
    SimulationHeader: typeof import('./src/components/SimulationHeader.vue')['default']
    SimulationSidebar: typeof import('./src/components/SimulationSidebar.vue')['default']
    SpecialtySection: typeof import('./src/components/specialty/SpecialtySection.vue')['default']
    StationListItem: typeof import('./src/components/StationListItem.vue')['default']
    TaskManager: typeof import('./src/components/TaskManager.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    WelcomeCard: typeof import('./src/components/WelcomeCard.vue')['default']
  }
}
